"""change count vectors

Revision ID: 44b7f08ebe43
Revises: fed55b625fb5
Create Date: 2026-07-15 02:04:31.212259

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "44b7f08ebe43"
down_revision: Union[str, Sequence[str], None] = "fed55b625fb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "review_rules",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "review_rules",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
